openapi: 3.0.1
info:
  title: PN Stream BE Microservice
  description: Documentation APIs v1.0
  termsOfService: https://termofservice.it
  x-api-id: api-internal-stream
  x-summary: 'Piattaforma Notifiche: API stream'
  version: '1.0.0'
  contact:
    email: pn@pagopa.it
  license:
    name: Licenza di PN
    url: 'https://da-definire/'
servers:
  - url: https://api.pn.pagopa.it
    description: Generated server url
paths:
  /status:
    get:
      summary: healthCheck path
      description: health check path per verificare lo stato del micro servizio
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
        '500':
          description: Internal Server Error

#  securitySchemes:                                      # ONLY EXTERNAL
#    bearerAuth:                                         # ONLY EXTERNAL
#      type: http                                        # ONLY EXTERNAL
#      scheme: bearer                                    # ONLY EXTERNAL
#      bearerFormat: JWT                                 # ONLY EXTERNAL
#security:                                               # ONLY EXTERNAL
# - bearerAuth: []                                       # ONLY EXTERNAL
              